[tool.black]
target-version = ["py310"]
extend-exclude = "third_party"

[tool.mypy]
ignore_missing_imports = true
exclude = ["third_party"]

[tool.pytest.ini_options]
norecursedirs = ["third_party"]

[tool.ruff]
extend-exclude = ["third_party"]
select = ["E", "F", "I", "W"]
ignore = ["E501"]
